# kubectl apply -f deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: age-detector-be
  namespace: franksalazar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: age-detector-be
  template:
    metadata:
      labels:
        app: age-detector-be
    spec:
      containers:
      - name: age-detector-be
        image: franksalazar45/api-service:latest   # Reemplaza con tu imagen DockerHub
        envFrom:
            - secretRef:
                name: credentials               # Cargar todo el Secret como variables de entorno