# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: franksalazar
type: Opaque
data:
  # Credenciales de la base de datos y RapidAPI en Base64
  DATABASE_USERNAME: cG9zdGdyZXMuaWlzdWRhanZycGNld2Z0dmxtcnM=
  POSTGRES_PASSWORD: NGdmZ2ZnZmZnOTIxNFE=

# echo -n "MICONTRASEÑA" | base64
# echo "ZGVtbzEyMw==" | base64 --decode
